Fix the crash when we do "portstat -d/-D" Also removed a unneccessary file
If the portstat cached file directory does not exist
the "portstat -d/-D" would crash.

This problem is especially exposed after this change:
dee262b65949f31a339e0dbf954e70cf6a0abb24
and the swss service would crash and system won't start

Sample Error log:
Traceback (most recent call last):
  File "/usr/bin/portstat", line 461, in <module>
    main()
  File "/usr/bin/portstat", line 390, in main
    if os.listdir(cnstat_dir) == []:
OSError: [Errno 2] No such file or directory: '/tmp/portstat'

    RB=1607629
    G=lnos-reviewers
    R=pchaudhary,pmao,samaity,sfardeen,zxu
    A=

Signed-off-by: Zhenggen Xu <zxu@linkedin.com>